stages:          # List of stages for jobs, and their order of execution
    - build:push

.artifact_version_branch:
  variables:
    IMAGE_VERSION: ${CI_COMMIT_BRANCH}-${CI_PIPELINE_ID}

.artifact_version_tag:
  variables:
    IMAGE_VERSION: ${CI_COMMIT_TAG}

.rules_publish:
  rules:
    - if: '$CI_COMMIT_BRANCH'
      variables:
        IMAGE_VERSION: !reference [.artifact_version_branch, variables, IMAGE_VERSION]
      #when: manual
    - if: '$CI_COMMIT_TAG && $CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+\.\d+$/'
      variables:
        IMAGE_VERSION: !reference [.artifact_version_tag, variables, IMAGE_VERSION]

docker:
  stage: build:push
  allow_failure: true
  tags:
    - docker-host
  needs: []
  extends:
   - .rules_publish
  image:
    name: gcr.io/kaniko-project/executor:v1.23.1-debug
    entrypoint: [""]
  before_script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${NEXUS_DOCKER_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${NEXUS_DOCKER_REGISTRY_USER}" "${NEXUS_DOCKER_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"},\"${SWORFISH_DOCKER}\":{\"auth\":\"$(printf "%s:%s" "${SWORFISH_DOCKER_USER}" "${SWORFISH_DOCKER_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - cat /kaniko/.docker/config.json
    - echo "${CA_CHAIN_PEM}" >> /kaniko/ssl/certs/ca-certificates.crt
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "./Dockerfile"
      --destination ${NEXUS_DOCKER_REGISTRY}/${CI_PROJECT_NAME}:${IMAGE_VERSION}
